services:
  pg:
    image: postgres:latest
    environment:
      POSTGRES_DB: dax
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - vol_pg:/var/lib/postgresql

volumes:
  vol_pg: