name: Deploy Web

on:
  push:
    branches: [ "main" ]
    paths:
      - 'client-flutter/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client-flutter

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Create .env file
        run: echo "${{ secrets.FLUTTER_ENV_FILE }}" > .env

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release --dart-define-from-file=.env

      - name: Deploy to Netlify
        run: |
          netlify deploy \
            --dir build/web \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }} \
            --prod

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web-build
          path: client-flutter/build/web